import Head from 'next/head';
import { useEffect } from 'react';
import { useRouter } from 'next/navigation';


export default function Home() {
  const {push} = useRouter();
  useEffect(()=>{
      push('/login');
  },[])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
    </>
  )
}
